version: '3'
services:
  redis:
    image: redis
    container_name: redis_url_redis
    ports:
      - "6379:6379"
  web:
    build: .
    container_name: redis_url_app
    ports:
      - "8080:8080"
    depends_on:
      - redis
